name: "New Release"

on:
  milestone:
    types: [closed]

env:
  GO: 1.16

jobs:
  bump-version:
    if: github.event_name == 'milestone'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_TOKEN }}

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO }}

      - name: Configure Git
        run: |
          git config user.name "sv-tools-bot"
          git config user.email "sv.go.tools@gmail.com"
          git fetch --all

      - name: Create Tag
        run: |
          docker run --rm -v $PWD:/mount -w /mount svtools/bumptag:latest ${{ github.event.milestone.title }}

      - name: Push Tag
        run: git push origin --tags
